### ISSUE TITLE
Recieved an error on install

### ISSUE THREAD

**Issue by shawn-hurley** [sabre1041/homebrew-openshift#1]
I was attempting to install and got an error.

Here is the log from homebrew

```
/usr/local/Cellar/apb/1.1.15-1/libexec/bin/pip
install
-v
--no-deps
--no-binary
:all:
--ignore-installed
/private/tmp/apb--apb-20180417-79548-1nwiopq/apb-1.1.15

Created temporary directory: /private/tmp/pip-ephem-wheel-cache-nHwJa8
Created temporary directory: /private/tmp/pip-install-MjMMmP
Processing /private/tmp/apb--apb-20180417-79548-1nwiopq/apb-1.1.15
  Created temporary directory: /private/tmp/pip-req-build-qbV0Ko
  Running setup.py (path:/private/tmp/pip-req-build-qbV0Ko/setup.py) egg_info for package from file:///private/tmp/apb--apb-20180417-79548-1nwiopq/apb-1.1.15
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-qbV0Ko/setup.py", line 2, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
Cleaning up...
  Removing source in /private/tmp/pip-req-build-qbV0Ko
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-req-build-qbV0Ko/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/apb/1.1.15-1/libexec/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/apb/1.1.15-1/libexec/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/usr/local/Cellar/apb/1.1.15-1/libexec/lib/python2.7/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/Cellar/apb/1.1.15-1/libexec/lib/python2.7/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/Cellar/apb/1.1.15-1/libexec/lib/python2.7/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/Cellar/apb/1.1.15-1/libexec/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 322, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/local/Cellar/apb/1.1.15-1/libexec/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 152, in prep_for_dist
    self.req.run_egg_info()
  File "/usr/local/Cellar/apb/1.1.15-1/libexec/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 486, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/Cellar/apb/1.1.15-1/libexec/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-req-build-qbV0Ko/

HOMEBREW_VERSION: 1.6.1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 5a2817cb023ca5e929fe030d423002992bdabf1b
Last commit: 24 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f10b7b6cda212e820428a922546639939c0ae88f
Core tap last commit: 69 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Users/shawn/Library/Caches/Homebrew
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.16.3 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_45
macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: 9.3
XQuartz: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by shawn-hurley** [comment]
it appears that this announcement might be related: https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html
